name: rappi-ml-challenge
channels:
  - conda-forge
dependencies:
  - python==3.7
  - numpy==1.19.2
  - pandas==1.1.2
  - scikit-learn==0.23.2
  - opencensus-ext-azure>=1.0.1
  - pip:
    - azureml-sdk